### ISSUE TITLE
Installation instructions - typo in list of packages

### ISSUE THREAD

**Issue by dkcoxie** [tstephie/UMICH-CDS-SR-scRNA-seq-Workshop-2022#1]
In the installation instructions, there is a mis-matched single quote around `BiocManager` (likely from Microsoft formatting) but the error was resolved by changing the code from
`list.of.packages <-c('tidyverse','Seurat','SeuratObject','pheatmap','RColorBrewer','scales','cowplot','patchwork','grid','gridExtra','harmony','knitr','rmarkdown',’ BiocManager’)`  
to 
`list.of.packages <-c('tidyverse','Seurat','SeuratObject','pheatmap','RColorBrewer','scales','cowplot','patchwork','grid','gridExtra','harmony','knitr','rmarkdown', 'BiocManager')`

**Comment by tstephie** [comment]
Yes, it should be updated in the Word document now!
